### ISSUE TITLE
Super Rocket Jumping Possible

### ISSUE THREAD

**Issue by lgtyqz** [HHSProgrammingClub/smash-my-buttons#11]
So basically what you do is
1. You walk Jack off the edge.
2. Move him back so that he touches the vertical edge of the platform.
3. Hold down the jump button.

Suggested solution: When jumping/recovering, set vertical velocity to 0 before applying the impulse.

**Comment by TheLordOfAllMuffins** [comment]
that sounds like a good idea

**Comment by lgtyqz** [comment]
ey fixed

**Comment by Nisnow** [comment]
Swiggity swibble, rocket jump not possible

**Comment by TheLordOfAllMuffins** [comment]
your rhyme fails to match in stress
it belongs on fail express
if you fail to speak in meter
you'll be shown the large egg beater
