### ISSUE TITLE
Fix DamageDisplayer positioning

### ISSUE THREAD

**Issue by lgtyqz** [HHSProgrammingClub/smash-my-buttons#22]
- Nisnow and lgtyqz can't see DamageDisplayer's content. Anyone else having these problems?

**Comment by Nisnow** [comment]
I actually fixed this yesterday but didn’t push changes. Will do later

**Comment by Nisnow** [comment]
Swiggity sway, [I fixed display ?](https://github.com/HHSProgrammingClub/smash-my-buttons/commit/fbaca598515995ccd37ae7e051e46c9dde41aa87)
