### ISSUE TITLE
Auto-canceling attacks

### ISSUE THREAD

**Issue by lgtyqz** [HHSProgrammingClub/smash-my-buttons#23]
I noticed with the new state system that attacking is a little odd now.

All of the following reset the attack animation and kill its associated hitbox:
- Sometimes, landing on the ground after attacking
- Jumping into a wall
- Performing another attack while doing an attack, which calls interruptStates()

Proposed solution: Use another method instead of interruptStates(), which checks if an attack is being performed and doesn't allow the interruption under those circumstances.

**Comment by lgtyqz** [comment]
Infinites are now possible against a wall.
For example, if you use Jack's tilt then immediately press a movement key, Jack will reset into his idle animation and is free to use his tilt again, even when the opponent is in hitstun.

Another example that is prone to abuse is Jack's recovery, which comes out basically frame 1 and can be cancelled by either pressing or releasing a movement key.

**Comment by TheLordOfAllMuffins** [comment]
The thing I'm working on, mentioned [here](https://github.com/HHSProgrammingClub/smash-my-buttons/commit/a5d1719a3cbd1789ee9e665b54b6d088520ae107) will give you the ability to solve this

**Comment by lgtyqz** [comment]
Another bug I've found—if you press an arrow key during an attack, the fixture can sometimes stay there and make move effects indefinite. Tried it with Jack's tilt and recovery.

**Comment by lgtyqz** [comment]
Solved with latest commit. However, now hatboxes spawn instantly when the animation is started.
Weird.
