### ISSUE TITLE
GUI Character Setting Bugs

### ISSUE THREAD

**Issue by lgtyqz** [HHSProgrammingClub/smash-my-buttons#28]
Few things that throw a bunch of red:
- If you select a character first from the combobox, then select and deselect the is AI checkbox, if you then press Start Fight! a NullPointerException() appears.
- If you select the AI checkbox, import a valid script, and then press Start Fight, a NullPointerException() appears.

The cause is that when the checkbox listener detects a change, an AIController() and PlayerController() object is created, but no character is attached to them until the combobox listener activates.

As for the second one, that's because there's no code in AIController() that binds a Character when the script is loaded.

**Comment by lgtyqz** [comment]
Fixed...I think? Will see in latest commits

**Comment by lgtyqz** [comment]
So now, if you select an AI, then change the character on the other, player-controlled, slot, the AI will think the player is at the origin.

To avoid this, change player character FIRST and THEN load the AI file.

We'd probably want to fix this pretty soon.

**Comment by TheLordOfAllMuffins** [comment]
it seems to be related to how the ai controller gets the enemy character -- now thet an m_enemy member for character exists, you may want to use that as the enemy instead of whatever is happening now

**Comment by TheLordOfAllMuffins** [comment]
i see the problem

**Comment by TheLordOfAllMuffins** [comment]
well in trying to fix this problem, i have found some strange behaviour in the battle thread where some code  - specifically inside the for loop at the top of gameLoop() - appears to not be executed for some reason
