### ISSUE TITLE
Edgewardo Recovery Issues Again

### ISSUE THREAD

**Issue by lgtyqz** [HHSProgrammingClub/smash-my-buttons#31]
So, after trying to hit someone with Edgy's recovery, I have determined that the hotbox associated with the end state doesn't spawn for some reason.

Setting the hitbox to be size 64000x64000 pixels does nothing.

What DOES do something is removing the removeHitbox and removeFixture methods in end().

Any idea what's going on?

**Comment by Nisnow** [comment]
I don’t remember if I specified a duration for his reappearance in his recovery. CharacterStates require durations now I believe.

**Comment by Nisnow** [comment]
Also note: working on a CharacterEffect class to display explosion, brooding fog, as well as Cam’s camera things

**Comment by Nisnow** [comment]
Swiggity swee, [I fixed Edge's recovery](https://github.com/HHSProgrammingClub/smash-my-buttons/commit/a036cf30baab25929af78f755805945f21f2cb9c).
