### ISSUE TITLE
Character State Stack Stuff — Auto-attacking

### ISSUE THREAD

**Issue by lgtyqz** [HHSProgrammingClub/smash-my-buttons#34]
So what happens is when a character attacks, if their move is interrupted by an opponent's attack before they use it, when the character is out of hitstun, they will automatically use the attack they just tried to use.

This can be problematic with, for example, Jack's telemarketing, because if interrupted, the telemarketing attack would play over again and give Jack no time to recover. Same goes for other long attacks, such as Birb's smash and Cam's tilt.

**Comment by TheLordOfAllMuffins** [comment]
auto-attacking is a really bad description of what was happening here
