### ISSUE TITLE
Win State/Lose State

### ISSUE THREAD

**Issue by lgtyqz** [HHSProgrammingClub/smash-my-buttons#36]
Exactly what it says on the tin. Display in SOME WAY which player won and what that AI's name & team is.

SOME WAY means any way.

**Comment by Nisnow** [comment]
Post-production: victory sprites for characters.
My quick idea for this is to add a low-opacity screen of black over the battle and display the text "You won, [AIAuthor name]!" or something similar. Display a few after a character lost their final stock.

**Comment by TheLordOfAllMuffins** [comment]
Got a basic thing going
