### ISSUE TITLE
Add Markers (name) to Characters for Mirror Matches

### ISSUE THREAD

**Issue by lgtyqz** [HHSProgrammingClub/smash-my-buttons#37]
Just display a colored name above each character.
BLUE (#0000FF) for Player 1, RED (#FFFF00) for Player 2. Get the name of the AI for this.

**Comment by Nisnow** [comment]
[That ain't red, falco.](https://github.com/HHSProgrammingClub/smash-my-buttons/commit/d8b6060d66fd0e41e2ef3634da97030c91a24cc5)
Now just gotta display names when characters are offscreen.
