### ISSUE TITLE
Realign Shockwaves

### ISSUE THREAD

**Issue by lgtyqz** [HHSProgrammingClub/smash-my-buttons#48]

**Comment by TheLordOfAllMuffins** [comment]
this would require the ability to offset sprites from the body

**Comment by TheLordOfAllMuffins** [comment]
i may also be possible by changing the positions of the fixtures and the bodies to bring up the positions of the bodies without changing the apparent positions of the fixtures

**Comment by lgtyqz** [comment]
Or do something in the projectile object to adjust
