### ISSUE TITLE
Birb Projectile E X T R E M E L Y stronk

### ISSUE THREAD

**Issue by lgtyqz** [HHSProgrammingClub/smash-my-buttons#54]
- Too Big
- Too Little Startup & End Lag
- Needs le knockback

**Comment by TheLordOfAllMuffins** [comment]
i was thinking it could be a thing to start combos by specifically *not* knocking back the opponent

**Comment by TheLordOfAllMuffins** [comment]
my idea was to use it as a punishable way to help close gaps if it hits

**Comment by lgtyqz** [comment]
eh not really a major tool atm, we'll leave it be as a stunner
