### ISSUE TITLE
Cam's Lingering Flashes

### ISSUE THREAD

**Issue by lgtyqz** [HHSProgrammingClub/smash-my-buttons#65]
Yeah, so apparently, sometimes hitbox fixtures will linger on the screen after the attack has finished, and in rarer circumstances, the sprites associated will as well. This is most noticeable with Edgy's tilt dash and Cam's spammed jab photo.

**Comment by Nisnow** [comment]
[Ad-hoc solution](https://github.com/HHSProgrammingClub/smash-my-buttons/commit/58bc2a25564708a4f3b24500045976c4a0538468) to be optimized post-production
