### ISSUE TITLE
Fix GUI Logic Failures

### ISSUE THREAD

**Issue by lgtyqz** [HHSProgrammingClub/smash-my-buttons#70]
Sometimes, the "Start Fight!" button flat-out doesn't work.
Dunno why—it may need some more investigating.

(also the users usually press "Run Script" before starting the fight)

**Comment by TheLordOfAllMuffins** [comment]
Can you give literally *any* other details? Any ways to reliably reproduce? Anything that seemed to be a pattern between these cases of X not working?

**Comment by TheLordOfAllMuffins** [comment]
Is the comment about the run script button related to this problem?

**Comment by lgtyqz** [comment]
See latest comment on
https://github.com/HHSProgrammingClub/smash-my-buttons/issues/28 for one
example.

**Comment by TheLordOfAllMuffins** [comment]
that's an unrelated problem

**Comment by TheLordOfAllMuffins** [comment]
I have not encountered this bug at all, and no additional helpful information has been provided

**Comment by Nisnow** [comment]
Neither my friend Max nor I am encountering this problem either.

**Comment by lgtyqz** [comment]
> Confirmed by Michel

**Comment by TheLordOfAllMuffins** [comment]
it's fixed if it was the nullPointerException from #28
